Smt build job
sillsdev/machine.py pull request #107
Opened 2024-05-06 19:11 UTC by johnml1135

Just like an NMT build job

2024-05-06 21:54 UTC, ddaspit reviewed
The truecasing model needs to be trained as well. I think this means that we will need to port the `UnigramTruecaser` class over to Python.

> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/107#-:-NxEt88PElHO-5yuoJwz:b-aiuayp)* status: 1 of 4 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-05-10 19:15 UTC, ddaspit requested changes
> Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 6 of 8 files at r3, 5 of 7 files at r4, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/107)* status: all files reviewed, 26 unresolved discussions (waiting on @johnml1135)

___
*[`machine/corpora/token_processors.py` line 17 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYhIFg5CTBEVFJ_fwz:-NxYhIFg5CTBEVFJ_fx-:bzbe37d) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/corpora/token_processors.py#L17)):*
> ```Python
> 
> 
> def _get_normalization_form(normalization_form: str) -> Literal["NFC", "NFD", "NFKC", "NFKD"]:
> ```

What is this for?
___
*[`machine/jobs/local_shared_file_service.py` line 10 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYvRpVCCCvolR5uYv8:-NxYvRpVCCCvolR5uYv9:btn93l) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/jobs/local_shared_file_service.py#L10)):*
> ```Python
> 
> 
> class LocalSharedFileService(SharedFileService):
> ```

You should export this class from the package `__init__.py` file.
___
*[`machine/jobs/smt_engine_build_job.py` line 25 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYsEjN8XvdmZ4Ds2sn:-NxYsEjN8XvdmZ4Ds2so:btn93l) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/jobs/smt_engine_build_job.py#L25)):*
> ```Python
> 
> 
> class SmtEngineBuildJob:
> ```

You should export this class from the package `__init__.py` file.
___
*[`machine/jobs/smt_engine_build_job.py` line 45 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYtN1v-gQosQRwiyCb:-NxYtN1v-gQosQRwiyCc:b7apcg5) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/jobs/smt_engine_build_job.py#L45)):*
> ```Python
>         with TemporaryDirectory() as temp_dir:
> 
>             parameters = ThotSmtParameters(
> ```

The model should be initialized from a blank model. See the `data/thot-new-model` directory in the `SIL.Machine.AspNetCore` project.
___
*[`machine/jobs/smt_engine_build_job.py` line 77 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYtv3E-uphuec-l9V_:-NxYtv3E-uphuec-l9Va:bngflo4) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/jobs/smt_engine_build_job.py#L77)):*
> ```Python
> 
>             with UnigramTruecaserTrainer(
>                 corpus=target_corpus, model_path=os.path.join(temp_dir, "truecase.txt"), tokenizer=tokenizer
> ```

The filename that we use in the Machine engine server is `unigram-casing-model.txt`.
___
*[`machine/statistics/conditional_frequency_distribution.py` line 7 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYkE7R-ydcyq6uqvhr:-NxYkE7R-ydcyq6uqvhs:b-6n3a4d) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/statistics/conditional_frequency_distribution.py#L7)):*
> ```Python
> 
> 
> @dataclass
> ```

I would prefer that this class is not a `dataclass`. `dataclass` is usually used for models/DTOs/records and not for normal classes.
___
*[`machine/statistics/conditional_frequency_distribution.py` line 8 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYvW9A3pUI3nyd2aHl:-NxYvW9A3pUI3nyd2aHm:btn93l) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/statistics/conditional_frequency_distribution.py#L8)):*
> ```Python
> 
> @dataclass
> class ConditionalFrequencyDistribution:
> ```

You should export this class from the package `__init__.py` file.
___
*[`machine/statistics/conditional_frequency_distribution.py` line 11 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYkIbqATk3zVUXEuim:-NxYkIbqATk3zVUXEuin:bplqtip) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/statistics/conditional_frequency_distribution.py#L11)):*
> ```Python
>     _freq_dist: Dict[str, FrequencyDistribution] = field(default_factory=dict)
> 
>     def get_conditions(self):
> ```

Don't forget the return type.
___
*[`machine/statistics/frequency_distribution.py` line 5 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYjJyz6RDZbXTITmFY:-NxYjJyz6RDZbXTITmFZ:b-3olf3w) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/statistics/frequency_distribution.py#L5)):*
> ```Python
> 
> 
> @dataclass
> ```

I would prefer that this class is not a `dataclass`.
___
*[`machine/statistics/frequency_distribution.py` line 6 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYvYjwDJOjLKReT74I:-NxYvYjwDJOjLKReT74J:btn93l) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/statistics/frequency_distribution.py#L6)):*
> ```Python
> 
> @dataclass
> class FrequencyDistribution:
> ```

You should export this class from the package `__init__.py` file.
___
*[`machine/tokenization/__init__.py` line 43 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYqRYQEryPYS37afCY:-NxYqRYQEryPYS37afCZ:b1ia96w) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/tokenization/__init__.py#L43)):*
> ```Python
> 
> 
> def get_tokenizer_detokenizer(name: str = "") -> Tuple[Tokenizer, Detokenizer]:
> ```

I would split this function into two functions: `create_tokenizer` and `create_detokenizer` and move them to the `tokenization_utils.py` module.
___
*[`machine/tokenization/__init__.py` line 45 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYql1J4dvy42-dUdoI:-NxYql1J4dvy42-dUdoJ:bz4coe2) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/tokenization/__init__.py#L45)):*
> ```Python
> def get_tokenizer_detokenizer(name: str = "") -> Tuple[Tokenizer, Detokenizer]:
>     name_lower = name.lower()
>     if "latin" in name_lower or name == "":
> ```

I would perform an equals check.
___
*[`machine/translation/unigram_truecaser.py` line 5 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYlacD04m97_3mb7fN:-NxYlacD04m97_3mb7fO:bv2oa8k) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/translation/unigram_truecaser.py#L5)):*
> ```Python
> from typing import Dict, Sequence, Tuple
> 
> from machine.corpora.text_corpus import TextCorpus
> ```

You should use relative imports.
___
*[`machine/translation/unigram_truecaser.py` line 12 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYlge-9pr78i5fQoKM:-NxYlge-9pr78i5fQoKN:b-3olf3w) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/translation/unigram_truecaser.py#L12)):*
> ```Python
> 
> 
> @dataclass
> ```

I would prefer that this class is not a `dataclass`.
___
*[`machine/translation/unigram_truecaser.py` line 13 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYvK8j1lGaysER21aB:-NxYvK8j1lGaysER21aC:btn93l) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/translation/unigram_truecaser.py#L13)):*
> ```Python
> 
> @dataclass
> class UnigramTruecaser(Truecaser):
> ```

You should export this class from the package `__init__.py` file.
___
*[`machine/translation/unigram_truecaser.py` line 33 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYmumF8ayL3OjsYDJb:-NxYmumF8ayL3OjsYDJc:bie52ir) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/translation/unigram_truecaser.py#L33)):*
> ```Python
> 
>     def create_trainer(self, corpus: TextCorpus) -> Trainer:
>         from machine.translation.unigram_truecaser_trainer import SubclassUnigramTruecaserTrainer
> `` [...]

2024-05-10 20:52 UTC, johnml1135 commented
*[`machine/corpora/token_processors.py` line 17 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYhIFg5CTBEVFJ_fwz:-NxZGZiq-4UzFkeGsbUr:b-zgc516) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/corpora/token_processors.py#L17)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

What is this for?
</blockquote></details>

Upgrading pyright threw and error - a difference between str and Literal.  This got rid of the error.  There could potentially be a better solution.


<!-- Sent from Reviewable.io -->

2024-05-20 13:38 UTC, johnml1135 commented
*[`machine/jobs/local_shared_file_service.py` line 10 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYvRpVCCCvolR5uYv8:-NyLDUWG95R9oDOsT-GI:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/jobs/local_shared_file_service.py#L10)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should export this class from the package `__init__.py` file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 13:42 UTC, johnml1135 commented
*[`machine/jobs/smt_engine_build_job.py` line 25 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYsEjN8XvdmZ4Ds2sn:-NyLEFCi6jfCbOjzyfOe:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/jobs/smt_engine_build_job.py#L25)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should export this class from the package `__init__.py` file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 13:59 UTC, johnml1135 commented
*[`machine/jobs/smt_engine_build_job.py` line 45 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYtN1v-gQosQRwiyCb:-NyLI73p1usdWg-lkJWf:btgodev) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/jobs/smt_engine_build_job.py#L45)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The model should be initialized from a blank model. See the `data/thot-new-model` directory in the `SIL.Machine.AspNetCore` project.
</blockquote></details>

Added new thot model


<!-- Sent from Reviewable.io -->

2024-05-20 13:59 UTC, johnml1135 commented
*[`machine/jobs/smt_engine_build_job.py` line 77 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYtv3E-uphuec-l9V_:-NyLI9VVD2GSSkQN3aRd:b-cypxrc) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/jobs/smt_engine_build_job.py#L77)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The filename that we use in the Machine engine server is `unigram-casing-model.txt`.
</blockquote></details>

updated.


<!-- Sent from Reviewable.io -->

2024-05-20 14:04 UTC, johnml1135 commented
*[`machine/statistics/conditional_frequency_distribution.py` line 7 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYkE7R-ydcyq6uqvhr:-NyLIJtg14TSZDGrLwnA:bb7f2mf) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/statistics/conditional_frequency_distribution.py#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would prefer that this class is not a `dataclass`. `dataclass` is usually used for models/DTOs/records and not for normal classes.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-05-20 14:06 UTC, johnml1135 commented
*[`machine/statistics/conditional_frequency_distribution.py` line 8 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYvW9A3pUI3nyd2aHl:-NyLJm9z6rfmRrKsl69b:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/statistics/conditional_frequency_distribution.py#L8)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should export this class from the package `__init__.py` file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 14:07 UTC, johnml1135 commented
*[`machine/statistics/frequency_distribution.py` line 5 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYjJyz6RDZbXTITmFY:-NyLJwgg7CqJeSCyvYJq:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/statistics/frequency_distribution.py#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would prefer that this class is not a `dataclass`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 14:07 UTC, johnml1135 commented
*[`machine/statistics/frequency_distribution.py` line 6 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYvYjwDJOjLKReT74I:-NyLJxmL3-WlElBQzJ4z:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/statistics/frequency_distribution.py#L6)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should export this class from the package `__init__.py` file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 14:14 UTC, johnml1135 commented
*[`machine/tokenization/__init__.py` line 43 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYqRYQEryPYS37afCY:-NyLLcdPALZmv9Z4048T:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/tokenization/__init__.py#L43)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would split this function into two functions: `create_tokenizer` and `create_detokenizer` and move them to the `tokenization_utils.py` module.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 14:15 UTC, johnml1135 commented
*[`machine/tokenization/__init__.py` line 45 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYql1J4dvy42-dUdoI:-NyLLmbLDE8zQjBIBIyk:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/tokenization/__init__.py#L45)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would perform an equals check.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 14:15 UTC, johnml1135 commented
*[`machine/translation/unigram_truecaser.py` line 5 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYlacD04m97_3mb7fN:-NyLLv6M1fNwwUEDnDSR:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/translation/unigram_truecaser.py#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should use relative imports.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 14:15 UTC, johnml1135 commented
*[`machine/translation/unigram_truecaser.py` line 12 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYlge-9pr78i5fQoKM:-NyLLul99Z65RHc54P9R:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/translation/unigram_truecaser.py#L12)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would prefer that this class is not a `dataclass`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 14:16 UTC, johnml1135 commented
*[`machine/translation/unigram_truecaser.py` line 13 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYvK8j1lGaysER21aB:-NyLM5pm92GH2aFeH0Bu:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/translation/unigram_truecaser.py#L13)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should export this class from the package `__init__.py` file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 14:50 UTC, johnml1135 commented
*[`machine/translation/unigram_truecaser.py` line 33 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYmumF8ayL3OjsYDJb:-NyLTp1x-lyraphMtFGU:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/translation/unigram_truecaser.py#L33)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

In order to avoid the circular reference, I think it would be fine to move the trainer classes into this file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 14:51 UTC, johnml1135 commented
*[`machine/translation/unigram_truecaser.py` line 88 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYnwzADRscfoIBIS2a:-NyLU0Mh7yTgLjaQHYEu:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/translation/unigram_truecaser.py#L88)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You can just call `clear` here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 14:51 UTC, johnml1135 commented
*[`machine/translation/unigram_truecaser.py` line 87 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYnjwODw-4kumB3P7c:-NyLTyH77lG-A9MSXgWb:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/translation/unigram_truecaser.py#L87)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You can just call `reset` here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 15:25 UTC, johnml1135 commented
*[`machine/translation/thot/thot_word_alignment_model_type.py` line 13 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYrD2-8FufUX-5hZUu:-NyLawzH71c95NjK0m_e:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/translation/thot/thot_word_alignment_model_type.py#L13)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Instead of using this function, update the `ThotSmtModel` and ThotSmtModelTrainer` classes to accept a `str` or `ThotWordAlignmentModelType` for the `word_alignment_model_type` parameter.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 15:26 UTC, johnml1135 commented
*[`tests/jobs/test_smt_engine_build_job.py` line 6 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYrpaPCqkyR1trh5Mh:-NyLb8jO7JysS0aL4GGM:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/tests/jobs/test_smt_engine_build_job.py#L6)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Instead of importing from the particular module, you should import from the top-level package.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 15:26 UTC, johnml1135 commented
*[`machine/translation/unigram_truecaser_trainer.py` line 4 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYoC6M58FdHKc5j9vV:-NyLbD0C5pZ2pM56YzCH:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/translation/unigram_truecaser_trainer.py#L4)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should use relative imports.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 15:27 UTC, johnml1135 commented
*[`machine/translation/unigram_truecaser_trainer.py` line 13 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYo7mZBuGGaKtsECju:-NyLbDkm50WrGbcI32mT:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/translation/unigram_truecaser_trainer.py#L13)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would prefer that this class is not a `dataclass`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 15:27 UTC, johnml1135 commented
*[`machine/translation/unigram_truecaser_trainer.py` line 14 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYvLtwBsZ10sO56kpa:-NyLbEoQ-VK8eFvHTa0M:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/translation/unigram_truecaser_trainer.py#L14)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should export this class from the package `__init__.py` file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 15:27 UTC, johnml1135 commented
*[`machine/translation/unigram_truecaser_trainer.py` line 30 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYuDmc9Waiwp-z7HXz:-NyLbQDF0sJ5PZ7-a-sN:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/translation/unigram_truecaser_trainer.py#L30)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

When iterating over a corpus, you should use the context manager to ensure that files are closed properly:
```
with self.corpus.tokenize(tokenizer=self.tokenizer).filter_nonempty().get_rows() as rows:
    for row in rows:
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 15:28 UTC, johnml1135 commented
*[`machine/translation/unigram_truecaser_trainer.py` line 44 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYol2u0q1L3Rgb4Eum:-NyLbSEk72jxO_soUVqm:b-mxlcrc) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/translation/unigram_truecaser_trainer.py#L44)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would prefix this with an underscore. I think `_UnigramTruecaserTrainer` should be fine.
</blockquote></details>

Since moving the class, the circular import is avoided and this class is unneeded.


<!-- Sent from Reviewable.io -->

2024-05-20 16:27 UTC, johnml1135 commented
*[`machine/translation/thot/thot_smt_model.py` line 89 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYpC3U1ww2kM2ztaJL:-NyLUzWL0TZhJl5klIkk:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/translation/thot/thot_smt_model.py#L89)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Leave this with a default of `None`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 19:25 UTC, ddaspit reviewed
> Reviewed 53 of 53 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/107)* status: all files reviewed, 15 unresolved discussions (waiting on @johnml1135)

___
*[`machine/corpora/token_processors.py` line 17 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYhIFg5CTBEVFJ_fwz:-NyMJ8DL7PvQf7nCnlLi:bzbhr16) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/corpora/token_processors.py#L17)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Upgrading pyright threw and error - a difference between str and Literal.  This got rid of the error.  There could potentially be a better solution.
</blockquote></details>

What if you made the type for the `normalization_form` of the `normalize` function: `Literal["NFC", "NFD", "NFKC", "NFKD"]`?
___
*[`machine/jobs/build_smt_engine.py` line 41 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMJsoC70V1bPsrJv-7:-NyMJsoC70V1bPsrJv-8:b-yla9pd) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/machine/jobs/build_smt_engine.py#L41)):*
> ```Python
> 
>         def clearml_progress(status: ProgressStatus) -> None:
>             nonlocal last_update_time  # Add this line to access the outer variable
> ```

I understand that `nonlocal` is not a common keyword, but I feel that this comment is unnecessary. The `nonlocal` keyword is sufficient documentation for the behavior.
___
*[`machine/jobs/smt_engine_build_job.py` line 21 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMKZha-nKk8zSb-SzR:-NyMKZhbA_XuliBoqOA7:b-96vdo) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/machine/jobs/smt_engine_build_job.py#L21)):*
> ```Python
> logger = logging.getLogger(__name__)
> 
> thot_new_model_directory = os.path.join(os.path.dirname(__file__), "thot-new-model")
> ```

This is a constant, so it should be in all caps.
___
*[`machine/statistics/conditional_frequency_distribution.py` line 11 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYkIbqATk3zVUXEuim:-NyMM0PM6sPTZgTcHTOL:b-dj89y8) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/statistics/conditional_frequency_distribution.py#L11)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I would make the type `Collection`. 
___
*[`machine/statistics/conditional_frequency_distribution.py` line 12 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMMLuZBTGWKaK-LLLt:-NyMMLuZBTGWKaK-LLLu:b-rb2w0g) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/machine/statistics/conditional_frequency_distribution.py#L12)):*
> ```Python
> 
>     def get_conditions(self) -> List[str]:
>         return list(self._freq_dist.keys())
> ```

There isn't a need to create a list instance.
___
*[`machine/tokenization/tokenization_utils.py` line 31 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMN7wBCnGlvAXTRLZu:-NyMN7wCDj8WitHaioF8:ba3as58) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/machine/tokenization/tokenization_utils.py#L31)):*
> ```Python
> 
> 
> def get_tokenizer(name: str = "") -> Tokenizer:
> ```

Naming it `create_tokenizer` and `create_detokenizer` makes it consistent with other similar functions in Machine, such as `create_thot_word_alignment_model`.
___
*[`machine/translation/unigram_truecaser.py` line 21 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMNlVyEPVyCL5ckU0g:-NyMNlVyEPVyCL5ckU0h:b-4rry0b) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/machine/translation/unigram_truecaser.py#L21)):*
> ```Python
>         self._bestTokens: Dict[str, Tuple[str, int]] = {}
> 
>     def __post_init__(self):
> ```

This code should be moved to the constructor.
___
*[`machine/translation/unigram_truecaser.py` line 36 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMOshH6MTkdYUOyOlT:-NyMOshH6MTkdYUOyOlU:brbcw7r) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/machine/translation/unigram_truecaser.py#L36)):*
> ```Python
> 
>     def create_trainer(self, corpus: TextCorpus) -> Trainer:
>         return UnigramTruecaserTrainer(corpus, self._model_path, self)
> ```

We don't want to update the state of the current `UnigramTruecaser` instance during training, so that we can continue to use it. The state of the instance should be updated when `Save` is called on the trainer. See the `UnigramTruecaser.Trainer` class in Machine for .NET.
___
*[`machine/translation/thot/thot_smt_model_trainer.py` line 40 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMPbAL22ivmcRVoH2y:-NyMPbAMEv1UR8w8EJLR:b-oomeo8) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/machine/translation/thot/thot_smt_model_trainer.py#L40)):*
> ```Python
> 
> 
> def getThotWordAlignmentModelType(model_type) -> ThotWordAlignmentModelType:
> ```

This should be snake case and prefixed with an underscore.
___
*[`machine/translation/thot/thot_smt_model_trainer.py` line 178 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMPt-s3LpxbsrFs5dN:-NyMPt-s3LpxbsrFs5dO:b-tc2lb6) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/machine/translation/thot/thot_smt_model_trainer.py#L178)):*
> ```Python
>         if type(word_alignment_model_type) is str:
>             word_alignment_model_type = getThotWordAlignmentModelType(word_alignment_model_type)
>         self._word_alignment_model_type: ThotWordAlignmentModelType = word_alignment_model_type  # type: ignore
> ```

Please don't ignore type warnings.
___
*[`tests/jobs/test_smt_engine_build_job.py` line 7 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMQOdtEM_-nI-hDU37:-NyMQOdtEM_-nI-hDU38:b-rljw49) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/tests/jobs/test_smt_engine_build_job.py#L7)):*
> ```Python
> 
> from machine.jobs import LocalSharedFileService, SmtEngineBuildJob
> from machine.jobs.config import SETTINGS
> ```

You should only import from the top-level packages, i.e. `machine.jobs`, `machine.utils`, etc.
___
*[`tests/translation/test_unigram_truecaser.py` line 3 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMREBi7ht9O1sG8G5q:-NyMREBi7ht9O1sG8G5r:bwm1k6b) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/tests/translation/test_unigram_truecaser.py#L3)):*
> ```Python
> from typing import Any, Iterable
> 
> from machine.corpora.memory_text import MemoryText
> ```

You should only import from the top-level packages, i.e. `machine.corpora`, `machine.translation`, etc.
___
*[`tests/translation/test_unigram_truecaser.py` line 9 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMRScx12_PBLp6GpHj:-NyMRScx12_PBLp6GpHk:bxkh8nx) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/tests/translation/test_unigram_truecaser.py#L9)):*
> ```Python
> from machine.translation.unigram_truecaser import UnigramTruecaser, UnigramTruecaserTrainer
> 
> training_segments = [
> ```

This is a constant, so it should be all caps.
___
*[`tests/translation/test_unigram_truecaser.py` line 72 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMR8R93s7GKZl96d6z:-NyMR8R93s7GKZl96d7-:b-eicinp) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/tests/translation/test_unigram_truecaser.py#L72)):*
> ```Python
> 
> 
> def test_compare_with_truecase_trainer() -> None:
> ```

I'm not sure I understand wh [...]

2024-05-21 11:35 UTC, johnml1135 commented
*[`machine/corpora/token_processors.py` line 17 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYhIFg5CTBEVFJ_fwz:-NyPv_fj3S-uYFpiOofO:bavyv2e) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/corpora/token_processors.py#L17)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

What if you made the type for the `normalization_form` of the `normalize` function: `Literal["NFC", "NFD", "NFKC", "NFKD"]`?
</blockquote></details>

If we do, it throws off the normalize function below - there are some instances where an arbitrary string is passed to it rather than a fixed string - and this conversion needs to happen somewhere.  Is there a better place for it?


<!-- Sent from Reviewable.io -->

2024-05-21 11:36 UTC, johnml1135 commented
*[`machine/jobs/build_smt_engine.py` line 41 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMJsoC70V1bPsrJv-7:-NyPvvTO69xWGlYBmfp9:b-ni3kyl) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/machine/jobs/build_smt_engine.py#L41)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I understand that `nonlocal` is not a common keyword, but I feel that this comment is unnecessary. The `nonlocal` keyword is sufficient documentation for the behavior.
</blockquote></details>

done - you can thank github copilot for the comment - and me for thinking it would be ok.


<!-- Sent from Reviewable.io -->

2024-05-21 11:37 UTC, johnml1135 commented
*[`machine/jobs/smt_engine_build_job.py` line 21 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMKZha-nKk8zSb-SzR:-NyPwExw39Kmv_8UBBir:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/machine/jobs/smt_engine_build_job.py#L21)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This is a constant, so it should be in all caps.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-21 11:37 UTC, johnml1135 commented
*[`machine/statistics/conditional_frequency_distribution.py` line 11 at r5](https://reviewable.io/reviews/sillsdev/machine.py/107#-NxYkIbqATk3zVUXEuim:-NyPwOVdASq_Af3DCUdM:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/87941fca3bcf20fa73c68c21979dc2f1ab9fbe82/machine/statistics/conditional_frequency_distribution.py#L11)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would make the type `Collection`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-21 11:38 UTC, johnml1135 commented
*[`machine/statistics/conditional_frequency_distribution.py` line 12 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMMLuZBTGWKaK-LLLt:-NyPwbiKCREUrXC4fHk-:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/machine/statistics/conditional_frequency_distribution.py#L12)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

There isn't a need to create a list instance.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-21 11:39 UTC, johnml1135 commented
*[`machine/tokenization/tokenization_utils.py` line 31 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMN7wBCnGlvAXTRLZu:-NyPwnPT0mdQOsOfRolf:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/machine/tokenization/tokenization_utils.py#L31)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Naming it `create_tokenizer` and `create_detokenizer` makes it consistent with other similar functions in Machine, such as `create_thot_word_alignment_model`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-21 11:55 UTC, johnml1135 commented
*[`machine/translation/unigram_truecaser.py` line 21 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMNlVyEPVyCL5ckU0g:-NyQ-TZvAv9xgJk-7-wv:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/machine/translation/unigram_truecaser.py#L21)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This code should be moved to the constructor.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-21 12:01 UTC, johnml1135 commented
*[`machine/translation/unigram_truecaser.py` line 36 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMOshH6MTkdYUOyOlT:-NyQ0h5i6TGYAo4OkxMe:b-uem5nk) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/machine/translation/unigram_truecaser.py#L36)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We don't want to update the state of the current `UnigramTruecaser` instance during training, so that we can continue to use it. The state of the instance should be updated when `Save` is called on the trainer. See the `UnigramTruecaser.Trainer` class in Machine for .NET.
</blockquote></details>

I don't understand exactly what you mean and what needs to be changed.


<!-- Sent from Reviewable.io -->

2024-05-21 12:17 UTC, johnml1135 commented
*[`machine/translation/thot/thot_smt_model_trainer.py` line 178 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMPt-s3LpxbsrFs5dN:-NyQ4QCX-ev9P_xVLk-x:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/machine/translation/thot/thot_smt_model_trainer.py#L178)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Please don't ignore type warnings.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-21 12:30 UTC, johnml1135 commented
*[`tests/translation/test_unigram_truecaser.py` line 3 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMREBi7ht9O1sG8G5q:-NyQ7PaAAK2bsZ5GGKL8:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/tests/translation/test_unigram_truecaser.py#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should only import from the top-level packages, i.e. `machine.corpora`, `machine.translation`, etc.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-21 12:30 UTC, johnml1135 commented
*[`tests/translation/test_unigram_truecaser.py` line 9 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMRScx12_PBLp6GpHj:-NyQ7T3b9Np4D5q3JFvu:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/tests/translation/test_unigram_truecaser.py#L9)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This is a constant, so it should be all caps.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-21 12:32 UTC, johnml1135 commented
*[`tests/translation/test_unigram_truecaser.py` line 72 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMR8R93s7GKZl96d6z:-NyQ7hbp5CiTHsoGM0pa:b-o5ksl9) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/tests/translation/test_unigram_truecaser.py#L72)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I'm not sure I understand what this is testing.
</blockquote></details>

Renamed function - testing that the trainer trains properly.


<!-- Sent from Reviewable.io -->

2024-05-23 12:00 UTC, johnml1135 commented
*[`dockerfile.cpu_only` line 1 at r7](https://reviewable.io/reviews/sillsdev/machine.py/107#-Ny_JUGb4dp-__mvXW56:-Ny_JUGb4dp-__mvXW57:bwhgm2y) ([raw file](https://github.com/sillsdev/machine.py/blob/ba850cff542e825efaf744c3648f66f2401cbb4d/dockerfile.cpu_only#L1)):*
> ```
> #compatability with Tensorflow 2.6.0 as per https://www.tensorflow.org/install/source#gpu
> ```

This has been untested - and unverified to build.  The CI routines need to be updated to create the image, push it to the GitHub container repo and pull it when doing CPU only jobs, and then verify it can actually work on the CPU shares.


<!-- Sent from Reviewable.io -->

2024-05-23 12:03 UTC, johnml1135 commented
*[`machine/translation/thot/thot_smt_model_trainer.py` line 156 at r7](https://reviewable.io/reviews/sillsdev/machine.py/107#-Ny_Ju6oEjx8C_LjJdPx:-Ny_Ju6oEjx8C_LjJdPy:b-58u8rp) ([raw file](https://github.com/sillsdev/machine.py/blob/ba850cff542e825efaf744c3648f66f2401cbb4d/machine/translation/thot/thot_smt_model_trainer.py#L156)):*
> ```Python
> 
> 
> class ThotSmtModelTrainer(Trainer):
> ```

This is around 10x slower than the dotnet implementation - why?  You can do comparative timing with SMT jobs being sent to either hangfire or ClearML.  For some reason, it's not multi threading as well as only using about 10% of one CPU.  I can't find any limiting happening anywhere (docker, ClearML, OpenMP, python, etc.).  Something with dynamically loaded libraries?  I don't know.


<!-- Sent from Reviewable.io -->

2024-06-10 20:05 UTC, ddaspit reviewed
> Reviewed 7 of 19 files at r7, 70 of 76 files at r8, 8 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/107)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`machine/jobs/thot/thot_smt_model_factory.py` line 95 at r9](https://reviewable.io/reviews/sillsdev/machine.py/107#-O-2j9fxEfcK7xE2FtY4:-O-2j9fxEfcK7xE2FtY5:bu2p0ch) ([raw file](https://github.com/sillsdev/machine.py/blob/91b0f42bdfdb0eaaf38f47ac74868530dcc547d7/machine/jobs/thot/thot_smt_model_factory.py#L95)):*
> ```Python
>             self._config.data_dir, self._config.shared_file_folder, "builds", self._config.build_id, "model"
>         )
>         return Path(shutil.make_archive(str(tar_file_basename), "zip", self._model_dir))
> ```

This should be saved as a `.tar.gz` file, so that it is consistent with the NMT factory.
___
*[`machine/translation/unigram_truecaser.py` line 36 at r6](https://reviewable.io/reviews/sillsdev/machine.py/107#-NyMOshH6MTkdYUOyOlT:-O-2iK7oAqdv2-dcYkiR:bb6un1j) ([raw file](https://github.com/sillsdev/machine.py/blob/fac590fcfb5f56a78ae46ba41095770572bf7661/machine/translation/unigram_truecaser.py#L36)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I don't understand exactly what you mean and what needs to be changed.
</blockquote></details>

Done
___
*[`machine/translation/thot/thot_smt_model_trainer.py` line 156 at r7](https://reviewable.io/reviews/sillsdev/machine.py/107#-Ny_Ju6oEjx8C_LjJdPx:-O-2jq3rEeCh2JUzp7Wk:bb6un1j) ([raw file](https://github.com/sillsdev/machine.py/blob/ba850cff542e825efaf744c3648f66f2401cbb4d/machine/translation/thot/thot_smt_model_trainer.py#L156)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This is around 10x slower than the dotnet implementation - why?  You can do comparative timing with SMT jobs being sent to either hangfire or ClearML.  For some reason, it's not multi threading as well as only using about 10% of one CPU.  I can't find any limiting happening anywhere (docker, ClearML, OpenMP, python, etc.).  Something with dynamically loaded libraries?  I don't know.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-06-10 20:46 UTC, johnml1135 commented
*[`machine/jobs/thot/thot_smt_model_factory.py` line 95 at r9](https://reviewable.io/reviews/sillsdev/machine.py/107#-O-2j9fxEfcK7xE2FtY4:-O-2tkDHEq_byu5DmsYA:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/91b0f42bdfdb0eaaf38f47ac74868530dcc547d7/machine/jobs/thot/thot_smt_model_factory.py#L95)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be saved as a `.tar.gz` file, so that it is consistent with the NMT factory.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-10 21:10 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/107#-:-O-2z48P92xfjL5ArBLJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2024-06-11 12:42 UTC, merged