Port USFM code from Machine up to commit c93f8dc
sillsdev/machine.py pull request #118
Opened 2024-08-30 01:37 UTC by mshannon-sil

This is the final PR for catching machine.py up to the USFM changes in Machine (until more USFM changes are added to Machine).

2024-08-30 01:55 UTC, mshannon-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/118)* status: 0 of 49 files reviewed, 3 unresolved discussions (waiting on @ddaspit)

___
*[`machine/corpora/memory_paratext_project_terms_parser.py` line 1 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5Vwq88DIdoUnDrw_r_:-O5Vwq88DIdoUnDrw_ra:b-xkll9p) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/memory_paratext_project_terms_parser.py#L1)):*
> ```Python
> from io import BytesIO
> ```

In Machine, this file is under the test folder. I moved it to machine/corpora because there are other similar "memory" files that are in the corpora folder, like usfm_memory_texts.py, that seem to only be used for tests. I can move it back to the test folder though if that would be preferable.
___
*[`machine/corpora/usfm_parser.py` line 72 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5VwYyd0nY66HF5B1fN:-O5VwYye6d3ODL_amkga:b-x84d7m) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/usfm_parser.py#L72)):*
> ```Python
>         self.state.index += 1
> 
>         assert self.state.token is not None
> ```

I moved up the assert statement in usfm parser so that the error checking tools don't complain about the possibility of self.state.token being None
___
*[`tests/corpora/test_paratext_project_terms_parser.py` line 9 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5VyYvP3_OUgp2kWBX0:-O5VyYvP3_OUgp2kWBX1:b8fl5ks) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/tests/corpora/test_paratext_project_terms_parser.py#L9)):*
> ```Python
>     UsfmStylesheet,
> )
> from machine.corpora.paratext_project_terms_parser_base import _get_glosses, _strip_parens
> ```

I know most of the time we just import from machine.corpora when we're in the test folder, rather than from the next level down inside the corpora module. However, that only works if the method is in the __init__.py, and I didn't think we wanted to add a private helper function for a class to __init__.py. Is there an issue with importing these specific methods the way I did? I also thought about making them static methods of the class they're helping, since they're static methods in Machine, but I've noticed that the preferred way to handle Machine's static methods has been to define them as private helper functions below the class.


<!-- Sent from Reviewable.io -->

2024-08-30 12:52 UTC, johnml1135 commented
*[`machine/corpora/usfm_text_base.py` line 53 at r1](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5YKudp0s8Z5i_IxZ4v:-O5YKudp0s8Z5i_IxZ4w:bhv6wfb) ([raw file](https://github.com/sillsdev/machine.py/blob/c348a6b763664efd3100662e62a2771f5d1291f1/machine/corpora/usfm_text_base.py#L53)):*
> ```Python
>                 f"{f' in project {self.project}' if self.project else ''}"
>                 f". Verse: {parser.state.verse_ref}, line: {parser.state.line_number}, "
>                 f"column: {parser.state.line_number}, error: '{e}'"
> ```

See https://github.com/sillsdev/machine/pull/236 - call it "character"


<!-- Sent from Reviewable.io -->

2024-08-30 12:54 UTC, johnml1135 commented
*[`tests/testutils/data/usfm/Tes/41MATTes.SFM` line 41 at r1](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5YLSNZ3R2lxJwf9i4i:-O5YLSN_7jelFJ_7L3ez:b-mf5ph9) ([raw file](https://github.com/sillsdev/machine.py/blob/c348a6b763664efd3100662e62a2771f5d1291f1/tests/testutils/data/usfm/Tes/41MATTes.SFM#L41)):*
> ```
> \v 6 Chapter two, verse \w six|strong="12345" \w*.
> \p
> \v 6 Bad verse. \x - \xo abc\xt 123\x* and more content.
> ```

Does this bring it up to match the tests fully?  Weren't there more changes than this?


<!-- Sent from Reviewable.io -->

2024-08-30 20:51 UTC, mshannon-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/118)* status: 0 of 49 files reviewed, 5 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`machine/corpora/usfm_text_base.py` line 53 at r1](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5YKudp0s8Z5i_IxZ4v:-O5_00aV5WirFPGAib_u:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/c348a6b763664efd3100662e62a2771f5d1291f1/machine/corpora/usfm_text_base.py#L53)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

See https://github.com/sillsdev/machine/pull/236 - call it "character"
</blockquote></details>

Done.
___
*[`tests/testutils/data/usfm/Tes/41MATTes.SFM` line 41 at r1](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5YLSNZ3R2lxJwf9i4i:-O5_0M9n7hGT5RMGiXb_:b-ss9ems) ([raw file](https://github.com/sillsdev/machine.py/blob/c348a6b763664efd3100662e62a2771f5d1291f1/tests/testutils/data/usfm/Tes/41MATTes.SFM#L41)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Does this bring it up to match the tests fully?  Weren't there more changes than this?
</blockquote></details>

There aren't any more changes than this that I'm aware of. Although maybe the changes you're thinking of were in my two previous PRs, since I ended up splitting the porting process into 3 chunks so that it would be easier to review.


<!-- Sent from Reviewable.io -->

2024-08-30 22:23 UTC, ddaspit requested changes
> Reviewed 3 of 11 files at r1, 4 of 5 files at r2, 7 of 7 files at r3, 2 of 5 files at r4, 3 of 7 files at r5, 2 of 2 files at r7, 1 of 3 files at r8, 1 of 3 files at r9, 5 of 9 files at r11, 3 of 3 files at r12, 18 of 18 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/118)* status: all files reviewed, 22 unresolved discussions (waiting on @johnml1135 and @mshannon-sil)

___
*[`machine/corpora/alignment_corpus.py` line 30 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5ZCJZF5xfrZYIMkcmF:-O5ZCJZF5xfrZYIMkcmG:b-nhrkru) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/alignment_corpus.py#L30)):*
> ```Python
>     def count(self, include_empty: bool = True, text_ids: Optional[Iterable[str]] = None) -> int:
>         with self.get_rows(text_ids) as rows:
>             return len(list(rows)) if include_empty else sum(1 for r in self.get_rows(text_ids) if not r.is_empty)
> ```

You accidentally called `get_rows` here. Just `sum(1 for row in rows if include_empty or not row.is_empty)` should be sufficient. This will avoid unnecessarily creating a `list` when `include_empty` is set to `True`.
___
*[`machine/corpora/alignment_corpus.py` line 50 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5ZC1Uj8H38hhnAdriT:-O5ZC1Uj8H38hhnAdriU:bxzexss) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/alignment_corpus.py#L50)):*
> ```Python
>         return _FilterAlignmentCorpus(self, predicate)
> 
>     def filter_texts(self, text_ids: Iterable[str]) -> AlignmentCorpus:
> ```

You should rename `text_ids` to `filter`, so that it is consistent with my comment on `TextCorpus`. Also, the parameter should be optional.
___
*[`machine/corpora/dictionary_alignment_corpus.py` line 3 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5ZBqOACu8Ri-CW8T52:-O5ZBqOACu8Ri-CW8T53:b-vb6zcc) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/dictionary_alignment_corpus.py#L3)):*
> ```Python
> from typing import Generator, Iterable, Optional, overload
> 
> from machine.corpora.alignment_row import AlignmentRow
> ```

This import should be relative.
___
*[`machine/corpora/dictionary_text_corpus.py` line 3 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5ZBt0FEmlOnkzUpijA:-O5ZBt0FEmlOnkzUpijB:b-vb6zcc) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/dictionary_text_corpus.py#L3)):*
> ```Python
> from typing import Generator, Iterable, Optional, overload
> 
> from machine.corpora.text_row import TextRow
> ```

This import should be relative.
___
*[`machine/corpora/memory_paratext_project_terms_parser.py` line 1 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5Vwq88DIdoUnDrw_r_:-O5ZD2GDAz7rkS_dk0ct:bhizdsd) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/memory_paratext_project_terms_parser.py#L1)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

In Machine, this file is under the test folder. I moved it to machine/corpora because there are other similar "memory" files that are in the corpora folder, like usfm_memory_texts.py, that seem to only be used for tests. I can move it back to the test folder though if that would be preferable.
</blockquote></details>

This was intentionally moved to the test folder. Because it defines "fake" files, it seems more like a test mock.
___
*[`machine/corpora/parallel_text_corpus.py` line 108 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5_Gl4c5IHPFjPKUWBA:-O5_Gl4c5IHPFjPKUWBB:b-jopxk5) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/parallel_text_corpus.py#L108)):*
> ```Python
>     def _get_rows(
>         self, text_ids: Optional[Iterable[str]] = None
>     ) -> ContextManagedGenerator[ParallelTextRow, None, None]: ...
> ```

The return type should be `Generator`.
___
*[`machine/corpora/parallel_text_corpus.py` line 594 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5_I4n6DYrIr2luXwWo:-O5_I4n6DYrIr2luXwWp:brq1yh7) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/parallel_text_corpus.py#L594)):*
> ```Python
>                 return len(self._df)
>             return len(self._df[(self._df[self._source_column] != "") & (self._df[self._target_column] != "")])
>         return sum(1 for row in self._get_rows(text_ids) if include_empty or not row.is_empty)
> ```

You should be able to filter the dataframe by the list of text ids. Something like this:
``` py
len(self._df[self._df[self._text_column].isin(text_ids_set)])
```
___
*[`machine/corpora/parallel_text_corpus.py` line 602 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5_HTf23zaWfksnTY37:-O5_HTf23zaWfksnTY38:bemlei3) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/parallel_text_corpus.py#L602)):*
> ```Python
>             if self._text_id_column is not None and self._text_id_column in self._df:
>                 text_id = cast(str, row[self._text_id_column])
>                 if text_ids_set is not None and text_id not in text_ids_set:
> ```

I would move this `if` up a level.
___
*[`machine/corpora/parallel_text_corpus.py` line 695 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5_JF1cDNa5mVGPMpcX:-O5_JF1cDNa5mVGPMpcY:bemlei3) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/parallel_text_corpus.py#L695)):*
> ```Python
>             if self._text_id_column is not None and self._text_id_column in example:
>                 text_id = cast(str, example[self._text_id_column])
>                 if text_ids_set is not None and text_id not in text_ids_set:
> ```

I would move this `if` up a level.
___
*[`machine/corpora/paratext_project_settings_parser_base.py` line 15 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5_K2Tm7LHXEiQI7dN-:-O5_K2TnDZZ8Ahq3vP3i:bnfojm4) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/paratext_project_settings_parser_base.py#L15)):*
> ```Python
> 
>     @abstractmethod
>     def exists(self, file_name: str) -> bool: ...
> ```

These methods should be prefixed with an underscore.
___
*[`machine/corpora/paratext_project_terms_parser_base.py` line 8 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5_KE-YA2DQwKHZ8_lH:-O5_KE-YA2DQwKHZ8_lI:br7h3nl) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/paratext_project_terms_parser_base.py#L8)):*
> ```Python
> from xml.etree import ElementTree
> 
> from machine.corpora.paratext_project_settings import ParatextProjectSettings
> ```

This should be a relative import.
___
*[`machine/corpora/paratext_project_terms_parser_base.py` line 92 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5_JvBxB5jIULBooXdj:-O5_JvBxB5jIULBooXdk:bnfojm4) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/paratext_project_terms_parser_base.py#L92)):*
> ```Python
> 
>     @abstractmethod
>     def exists(self, file_name: str) -> bool: ...
> ```

These methods should be prefixed with an underscore.
___
*[`machine/corpora/paratext_project_text_updater_base.py` line 23 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5_L0B52iDd80ZvtsA6:-O5_L0B52iDd80ZvtsA7:bxl43fq) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/paratext_project_text_updater_base.p [...]

2024-09-04 03:49 UTC, mshannon-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/118)* status: all files reviewed, 22 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`machine/corpora/alignment_corpus.py` line 30 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5ZCJZF5xfrZYIMkcmF:-O5udeVa77EmS-niMFpy:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/alignment_corpus.py#L30)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You accidentally called `get_rows` here. Just `sum(1 for row in rows if include_empty or not row.is_empty)` should be sufficient. This will avoid unnecessarily creating a `list` when `include_empty` is set to `True`.
</blockquote></details>

Done.
___
*[`machine/corpora/alignment_corpus.py` line 50 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5ZC1Uj8H38hhnAdriT:-O5uhkqaE9ovRmfZ0ePH:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/alignment_corpus.py#L50)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should rename `text_ids` to `filter`, so that it is consistent with my comment on `TextCorpus`. Also, the parameter should be optional.
</blockquote></details>

Done.
___
*[`machine/corpora/dictionary_alignment_corpus.py` line 3 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5ZBqOACu8Ri-CW8T52:-O5ui1oNE2NBXCPl3hKp:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/dictionary_alignment_corpus.py#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This import should be relative.
</blockquote></details>

Done.
___
*[`machine/corpora/dictionary_text_corpus.py` line 3 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5ZBt0FEmlOnkzUpijA:-O5uiCkj3ltVW-x_RycB:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/dictionary_text_corpus.py#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This import should be relative.
</blockquote></details>

Done.
___
*[`machine/corpora/memory_paratext_project_terms_parser.py` line 1 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5Vwq88DIdoUnDrw_r_:-O5uiSUVCRYidYnL_UWN:b-f2u7j5) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/memory_paratext_project_terms_parser.py#L1)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This was intentionally moved to the test folder. Because it defines "fake" files, it seems more like a test mock.
</blockquote></details>

Should we move all the memory files to the test folder then?
___
*[`machine/corpora/parallel_text_corpus.py` line 108 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5_Gl4c5IHPFjPKUWBA:-O5uj8Y37QWkIG1w9che:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/parallel_text_corpus.py#L108)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The return type should be `Generator`.
</blockquote></details>

Done.
___
*[`machine/corpora/parallel_text_corpus.py` line 594 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5_I4n6DYrIr2luXwWo:-O5unldv0M6wOWYVQApX:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/parallel_text_corpus.py#L594)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should be able to filter the dataframe by the list of text ids. Something like this:
``` py
len(self._df[self._df[self._text_column].isin(text_ids_set)])
```
</blockquote></details>

Done.
___
*[`machine/corpora/parallel_text_corpus.py` line 602 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5_HTf23zaWfksnTY37:-O5uowvj0QnQF7M48xH9:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/parallel_text_corpus.py#L602)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would move this `if` up a level.
</blockquote></details>

Done.
___
*[`machine/corpora/parallel_text_corpus.py` line 695 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5_JF1cDNa5mVGPMpcX:-O5up68X6Oz4ie7BX8YN:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/parallel_text_corpus.py#L695)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would move this `if` up a level.
</blockquote></details>

Done.
___
*[`machine/corpora/paratext_project_settings_parser_base.py` line 15 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5_K2Tm7LHXEiQI7dN-:-O5ux2NACaL2B73p_yR2:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/paratext_project_settings_parser_base.py#L15)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

These methods should be prefixed with an underscore.
</blockquote></details>

Done.
___
*[`machine/corpora/paratext_project_terms_parser_base.py` line 8 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5_KE-YA2DQwKHZ8_lH:-O5ux6H9CxS6abXV1ipq:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/paratext_project_terms_parser_base.py#L8)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be a relative import.
</blockquote></details>

Done.
___
*[`machine/corpora/paratext_project_terms_parser_base.py` line 92 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5_JvBxB5jIULBooXdj:-O5ux7Qh5XKbMqAAGoqo:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/paratext_project_terms_parser_base.py#L92)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

These methods should be prefixed with an underscore.
</blockquote></details>

Done.
___
*[`machine/corpora/paratext_project_text_updater_base.py` line 23 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5_L0B52iDd80ZvtsA6:-O5uzBR73Nesb1ExGI1N:bpy7s3p) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/paratext_project_text_updater_base.py#L23)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Instead of `List`, you should use `Sequence`.
</blockquote></details>

Done.   I also changed it for some other function definitions where Machine specified an `IReadOnlyList`.
___
*[`machine/corpora/paratext_project_text_updater_base.py` line 48 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5_KrU8E7sj31zpvPmV:-O5uyVf54XTBFxQiGjTo:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/paratext_project_text_updater_base.py#L48)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

These methods should be prefixed with an underscore.
</blockquote></details>

Done.
___
*[`machine/corpora/text_corpus.py` line 45 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5Z6QqLBAEz1DL5NC8B:-O5uduG52DjmCVmnfr63:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/text_corpus.py#L45)):*
<details><summary><i>Previously, ddaspit  [...]

2024-09-04 11:37 UTC, johnml1135 commented
*[`tests/testutils/data/usfm/Tes/41MATTes.SFM` line 41 at r1](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5YLSNZ3R2lxJwf9i4i:-O5wooBM59_VMY7gOaWb:b-svhrrt) ([raw file](https://github.com/sillsdev/machine.py/blob/c348a6b763664efd3100662e62a2771f5d1291f1/tests/testutils/data/usfm/Tes/41MATTes.SFM#L41)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

There aren't any more changes than this that I'm aware of. Although maybe the changes you're thinking of were in my two previous PRs, since I ended up splitting the porting process into 3 chunks so that it would be easier to review.
</blockquote></details>

Ok - I am not reviewing in depth, I am just wanting to make sure that the testing is the same between the two.


<!-- Sent from Reviewable.io -->

2024-09-05 18:20 UTC, ddaspit reviewed
> Reviewed 24 of 24 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/118)* status: all files reviewed, 2 unresolved discussions (waiting on @mshannon-sil)



<!-- Sent from Reviewable.io -->

2024-09-05 18:21 UTC, ddaspit reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/118)* status: all files reviewed, 2 unresolved discussions (waiting on @mshannon-sil)

___
*[`machine/corpora/memory_paratext_project_terms_parser.py` line 1 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5Vwq88DIdoUnDrw_r_:-O62PiMdAYUaGmrab9Dj:b2cxpma) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/memory_paratext_project_terms_parser.py#L1)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

Should we move all the memory files to the test folder then?
</blockquote></details>

As we discussed in the standup, you just need to move this class.


<!-- Sent from Reviewable.io -->

2024-09-05 18:52 UTC, mshannon-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/118)* status: 50 of 53 files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[`machine/corpora/memory_paratext_project_terms_parser.py` line 1 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5Vwq88DIdoUnDrw_r_:-O62W-AZ0lpcEAKIrnEc:b85bogt) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/memory_paratext_project_terms_parser.py#L1)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

As we discussed in the standup, you just need to move this class.
</blockquote></details>

Done. And just to confirm, it's okay that I'm importing it as `from tests.corpora.memory_paratext_project_terms_parser import MemoryParatextProjectTermsParser` right? I first tried to just use `from .memory_paratext_project_terms_parser import MemoryParatextProjectTermsParser, but that caused a pytest test discovery error, so I think there's something about how packages work that I might not be understanding.


<!-- Sent from Reviewable.io -->

2024-09-05 18:53 UTC, mshannon-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/118)* status: 50 of 53 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`tests/testutils/data/usfm/Tes/41MATTes.SFM` line 41 at r1](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5YLSNZ3R2lxJwf9i4i:-O62X44B3qXIf8dAsvYH:b-ny8iq4) ([raw file](https://github.com/sillsdev/machine.py/blob/c348a6b763664efd3100662e62a2771f5d1291f1/tests/testutils/data/usfm/Tes/41MATTes.SFM#L41)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Ok - I am not reviewing in depth, I am just wanting to make sure that the testing is the same between the two.
</blockquote></details>

Yes, the test cases look to match up between both repos.


<!-- Sent from Reviewable.io -->

2024-09-05 19:06 UTC, ddaspit approved these changes
> Reviewed 3 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/118)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`machine/corpora/memory_paratext_project_terms_parser.py` line 1 at r13](https://reviewable.io/reviews/sillsdev/machine.py/118#-O5Vwq88DIdoUnDrw_r_:-O62_19t7Tpsy0B2zuHd:b-n7o69x) ([raw file](https://github.com/sillsdev/machine.py/blob/ff1c067ace1847e8d53b002f2309c85b5662a785/machine/corpora/memory_paratext_project_terms_parser.py#L1)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

Done. And just to confirm, it's okay that I'm importing it as `from tests.corpora.memory_paratext_project_terms_parser import MemoryParatextProjectTermsParser` right? I first tried to just use `from .memory_paratext_project_terms_parser import MemoryParatextProjectTermsParser, but that caused a pytest test discovery error, so I think there's something about how packages work that I might not be understanding.
</blockquote></details>

Yes, that is perfectly fine.


<!-- Sent from Reviewable.io -->

2024-09-05 20:45 UTC, merged