fix deprecated tokenizer methods, add test cases
sillsdev/machine.py pull request #139
Opened 2024-11-06 18:05 UTC by mshannon-sil

This PR removes the lang_code_to_id method in places where it could be used by the NllbTokenizer, due to NllbTokenizer deprecating that method, and keeps it for the tokenizers that still use it. In its place, I compare against `tokenizer.added_tokens_encoder`, since that's what huggingface uses as their check inside their `tokenizer.convert_tokens_to_ids`, which was already being used in the `add_lang_code_to_tokenizer` method for obtaining the lang_id from the lang_code. I also added test cases for each of the different tokenizer types supported by machine.py.

2024-11-06 20:56 UTC, ddaspit requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/139)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135 and @mshannon-sil)

___
*[`machine/translation/huggingface/hugging_face_nmt_model_trainer.py` line 401 at r1](https://reviewable.io/reviews/sillsdev/machine.py/139#-OB2FX1SAtygDZHsKyKJ:-OB2FX1SAtygDZHsKyKK:b5k8r55) ([raw file](https://github.com/sillsdev/machine.py/blob/1fe806e0d2aa53f8e93554bcfe5d03190f7d0bc4/machine/translation/huggingface/hugging_face_nmt_model_trainer.py#L401)):*
> ```Python
> 
> 
> def _add_lang_code_to_tokenizer(tokenizer: Union[PreTrainedTokenizer, PreTrainedTokenizerFast], lang_code: str):
> ```

You can just make this a "public" function (i.e. from the underscore) and export it from the "huggingface" package.


<!-- Sent from Reviewable.io -->

2024-11-06 21:27 UTC, mshannon-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/139)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`machine/translation/huggingface/hugging_face_nmt_model_trainer.py` line 401 at r1](https://reviewable.io/reviews/sillsdev/machine.py/139#-OB2FX1SAtygDZHsKyKJ:-OB2N0CGCWqlshfa-eEQ:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/1fe806e0d2aa53f8e93554bcfe5d03190f7d0bc4/machine/translation/huggingface/hugging_face_nmt_model_trainer.py#L401)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You can just make this a "public" function (i.e. from the underscore) and export it from the "huggingface" package.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-06 22:01 UTC, johnml1135 commented
*[`machine/translation/huggingface/hugging_face_nmt_engine.py` line 82 at r2](https://reviewable.io/reviews/sillsdev/machine.py/139#-OB2Uo490_Is4u7yHUZK:-OB2Uo490_Is4u7yHUZL:bgp997w) ([raw file](https://github.com/sillsdev/machine.py/blob/2269ae024a80678e37ac8a263a8f89d7056347bc/machine/translation/huggingface/hugging_face_nmt_engine.py#L82)):*
> ```Python
>             else:
>                 src_lang_token = src_lang
>                 tgt_lang_token = tgt_lang
> ```

Is this code tested?


<!-- Sent from Reviewable.io -->

2024-11-06 22:02 UTC, johnml1135 reviewed
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/139)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit and @mshannon-sil)



<!-- Sent from Reviewable.io -->

2024-11-06 22:19 UTC, mshannon-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/139)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`machine/translation/huggingface/hugging_face_nmt_engine.py` line 82 at r2](https://reviewable.io/reviews/sillsdev/machine.py/139#-OB2Uo490_Is4u7yHUZK:-OB2YIZkDYxK6uj52_Pq:b-bnehsd) ([raw file](https://github.com/sillsdev/machine.py/blob/2269ae024a80678e37ac8a263a8f89d7056347bc/machine/translation/huggingface/hugging_face_nmt_engine.py#L82)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Is this code tested?
</blockquote></details>

Yes, although not rigorously. The if statement is covered by `test_translate_greedy` in `test_huggingface_nmt_engine.py`, which uses the  "stas/tiny-m2m_100" model and corresponding M2M100Tokenizer. And the basic functionality of using the `lang_code_to_token` method for M2M100Tokenizer is also tested in the new test case I added `test_m2m_100_tokenizer_add_lang_code()` in `test_hugginface_nmt_model_trainer.py`.


<!-- Sent from Reviewable.io -->

2024-11-07 14:36 UTC, johnml1135 approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/139)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2024-11-07 19:28 UTC, ddaspit reviewed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/139)* status: all files reviewed, 1 unresolved discussion (waiting on @mshannon-sil)

___
*[`tests/translation/huggingface/test_hugging_face_nmt_model_trainer.py` line 25 at r2](https://reviewable.io/reviews/sillsdev/machine.py/139#-OB75G6t9beRKRTvN19E:-OB75G6t9beRKRTvN19F:bcqnogz) ([raw file](https://github.com/sillsdev/machine.py/blob/2269ae024a80678e37ac8a263a8f89d7056347bc/tests/translation/huggingface/test_hugging_face_nmt_model_trainer.py#L25)):*
> ```Python
> from machine.corpora import DictionaryTextCorpus, MemoryText, TextRow
> from machine.translation.huggingface import HuggingFaceNmtEngine, HuggingFaceNmtModelTrainer
> from machine.translation.huggingface.hugging_face_nmt_model_trainer import add_lang_code_to_tokenizer
> ```

Yoiu should import the function directly from the `machine.translation.huggingface` package.


<!-- Sent from Reviewable.io -->

2024-11-07 20:49 UTC, mshannon-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/139)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[`tests/translation/huggingface/test_hugging_face_nmt_model_trainer.py` line 25 at r2](https://reviewable.io/reviews/sillsdev/machine.py/139#-OB75G6t9beRKRTvN19E:-OB7No3x4mt4v1aOvW_j:biev4vq) ([raw file](https://github.com/sillsdev/machine.py/blob/2269ae024a80678e37ac8a263a8f89d7056347bc/tests/translation/huggingface/test_hugging_face_nmt_model_trainer.py#L25)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Yoiu should import the function directly from the `machine.translation.huggingface` package.
</blockquote></details>

Ope sorry I overlooked that, I'll go ahead and make the quick change.


<!-- Sent from Reviewable.io -->

2024-11-07 21:00 UTC, mshannon-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/139)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`tests/translation/huggingface/test_hugging_face_nmt_model_trainer.py` line 25 at r2](https://reviewable.io/reviews/sillsdev/machine.py/139#-OB75G6t9beRKRTvN19E:-OB7QNK-7kzw3JRp1a0P:b-896fix) ([raw file](https://github.com/sillsdev/machine.py/blob/2269ae024a80678e37ac8a263a8f89d7056347bc/tests/translation/huggingface/test_hugging_face_nmt_model_trainer.py#L25)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

Ope sorry I overlooked that, I'll go ahead and make the quick change.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-08 16:30 UTC, johnml1135 approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/139)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2024-11-08 17:31 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/139#-:-OBBpGCU2tdL8MuH7wYW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)



<!-- Sent from Reviewable.io -->

2024-11-08 17:34 UTC, merged