catch all errors and mark clearml task as failed with status_reason
sillsdev/machine.py pull request #29
Opened 2023-09-14 03:15 UTC by mshannon-sil

I added a try except block that will first log any error and then, if it's running on clearml, will call `mark_failed()` with the error message as the `status_reason`. This `status_reason` can then be accessed by machine to pass along to the user.

2023-09-14 03:20 UTC, mshannon-sil commented
I see that the checks are failing. I'll remove the review requests until they're passing.

2023-09-14 11:26 UTC, johnml1135 commented
*[`machine/jobs/build_nmt_engine.py` line 63 at r1](https://reviewable.io/reviews/sillsdev/machine.py/29#-NeIQSFJE2bJPyU7olLK:-NeIQSFJE2bJPyU7olLL:b-mpbb1h) ([raw file](https://github.com/sillsdev/machine.py/blob/98ce526e8c3c726645ec18cdf55aaec2863ad68d/machine/jobs/build_nmt_engine.py#L63)):*
> ```Python
>         logger.exception(str(e))
>         if task:
>             task.mark_failed(status_reason=str(e))
> ```

Wouldn't it be better for `status_reason=type(exception).__name__,status_message=str(e)`


<!-- Sent from Reviewable.io -->

2023-09-14 11:27 UTC, johnml1135 commented
*[`machine/jobs/build_nmt_engine.py` line 61 at r1](https://reviewable.io/reviews/sillsdev/machine.py/29#-NeIRQOR4sMLRLw0YRGb:-NeIRQOR4sMLRLw0YRGc:b-qb5zzo) ([raw file](https://github.com/sillsdev/machine.py/blob/98ce526e8c3c726645ec18cdf55aaec2863ad68d/machine/jobs/build_nmt_engine.py#L61)):*
> ```Python
>         logger.info("Finished")
>     except Exception as e:
>         logger.exception(str(e))
> ```

Should this be if task, then mark_failed, else logger?  If tasks exists, does it double-log the error?


<!-- Sent from Reviewable.io -->

2023-09-14 11:27 UTC, johnml1135 reviewed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/29)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit and @mshannon-sil)



<!-- Sent from Reviewable.io -->

2023-09-14 13:44 UTC, mshannon-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/29)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`machine/jobs/build_nmt_engine.py` line 61 at r1](https://reviewable.io/reviews/sillsdev/machine.py/29#-NeIRQOR4sMLRLw0YRGb:-NeIrcdv0DN17jOBOZ7Y:b-ajqb5y) ([raw file](https://github.com/sillsdev/machine.py/blob/98ce526e8c3c726645ec18cdf55aaec2863ad68d/machine/jobs/build_nmt_engine.py#L61)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Should this be if task, then mark_failed, else logger?  If tasks exists, does it double-log the error?
</blockquote></details>

`mark_failed()` does not log any output to the console, it just sets the clearml task as failed and sets the corresponding `status_reason` and `status_message` of the task. That's why I had the logger run in all cases. However, something I was considering was simply raising the exception again at the end of the except block rather than logging the error, since raising the exception prints the full traceback unlike the logger which only includes the final line in the traceback. Would this be preferable in your opinion?
___
*[`machine/jobs/build_nmt_engine.py` line 63 at r1](https://reviewable.io/reviews/sillsdev/machine.py/29#-NeIQSFJE2bJPyU7olLK:-NeIqs-BB_lbnEONfn2y:bmsxghq) ([raw file](https://github.com/sillsdev/machine.py/blob/98ce526e8c3c726645ec18cdf55aaec2863ad68d/machine/jobs/build_nmt_engine.py#L63)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Wouldn't it be better for `status_reason=type(exception).__name__,status_message=str(e)`
</blockquote></details>

Good idea, I'll make that change.


<!-- Sent from Reviewable.io -->

2023-09-14 20:06 UTC, johnml1135 commented
*[`machine/jobs/build_nmt_engine.py` line 61 at r1](https://reviewable.io/reviews/sillsdev/machine.py/29#-NeIRQOR4sMLRLw0YRGb:-NeKI5hi9qQTYlTSGvAN:bkpo9jk) ([raw file](https://github.com/sillsdev/machine.py/blob/98ce526e8c3c726645ec18cdf55aaec2863ad68d/machine/jobs/build_nmt_engine.py#L61)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

`mark_failed()` does not log any output to the console, it just sets the clearml task as failed and sets the corresponding `status_reason` and `status_message` of the task. That's why I had the logger run in all cases. However, something I was considering was simply raising the exception again at the end of the except block rather than logging the error, since raising the exception prints the full traceback unlike the logger which only includes the final line in the traceback. Would this be preferable in your opinion?
</blockquote></details>

I would prefer the whole traceback in the log - it is for diagnosis above all.  The whole traceback is not needed in mark_failed - as that is more for the user than the engineer.


<!-- Sent from Reviewable.io -->

2023-09-14 20:06 UTC, johnml1135 requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/29)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit and @mshannon-sil)



<!-- Sent from Reviewable.io -->

2023-09-14 22:08 UTC, ddaspit reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/29)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`machine/jobs/build_nmt_engine.py` line 61 at r1](https://reviewable.io/reviews/sillsdev/machine.py/29#-NeIRQOR4sMLRLw0YRGb:-NeKj8Lq1JfqgAXa5Fql:b-4vn1nh) ([raw file](https://github.com/sillsdev/machine.py/blob/98ce526e8c3c726645ec18cdf55aaec2863ad68d/machine/jobs/build_nmt_engine.py#L61)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I would prefer the whole traceback in the log - it is for diagnosis above all.  The whole traceback is not needed in mark_failed - as that is more for the user than the engineer.
</blockquote></details>

I was under the impression that `logger.exeception` prints the full stack trace.


<!-- Sent from Reviewable.io -->

2023-09-14 22:55 UTC, mshannon-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/29)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`machine/jobs/build_nmt_engine.py` line 61 at r1](https://reviewable.io/reviews/sillsdev/machine.py/29#-NeIRQOR4sMLRLw0YRGb:-NeKqpMh2vmvHlK3s1GP:b18ny) ([raw file](https://github.com/sillsdev/machine.py/blob/98ce526e8c3c726645ec18cdf55aaec2863ad68d/machine/jobs/build_nmt_engine.py#L61)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I was under the impression that `logger.exeception` prints the full stack trace.
</blockquote></details>

The default behavior for `logger.exception()` only prints out the final line in the stack trace, but I looked into it and saw that if you set `stack_trace=True` it will print the whole stack trace. I went ahead and added that in my most recent commit. Also, I discovered that if I call `raise` at the end of the except block, it somehow is overwriting the `status_reason` and `status_message` that I set for the task, so using raise wasn't a tenable solution anyways.


<!-- Sent from Reviewable.io -->

2023-09-15 14:45 UTC, mshannon-sil commented
@johnml1135 @ddaspit All of the review comments have been addressed now. And it looks like the checks failing isn't related to any of the code I added, since they're failing for the current commit in main too. I can do a separate pull request investigating those issues, but for now I think we should go forward with merging the error reporting into main.

2023-09-15 18:05 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/29#-:-NeP0E2Q6IAxStY1H_LN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2023-09-15 19:52 UTC, johnml1135 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine.py/29)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)



<!-- Sent from Reviewable.io -->

2023-09-15 19:53 UTC, merged